# suggestions.py

improvement_suggestions = {
    'noisy': 'Consider using a quieter cooling system',
    'price': 'Look for discounts or cheaper alternatives',
    'battery': 'Consider improving battery life',
    'performance': 'Improve performance for better user experience',
    'heat': 'Enhance cooling solutions to manage heat better',
    'weight': 'Consider reducing the weight for better portability',
    'size': 'Optimize the size for better fit and comfort',
    'durability': 'Improve durability for longer lifespan',
    'speed': 'Enhance speed for better performance',
    'connectivity': 'Consider improving connectivity options',
    'design': 'Enhance the design for better aesthetics',
    'support': 'Provide better customer support',
    'warranty': 'Extend the warranty period',
    'features': 'Add more features for better user experience',
    'compatibility': 'Improve compatibility with other devices',
    'software': 'Update software for better functionality',
    'hardware': 'Upgrade hardware for better performance',
    'quality': 'Improve quality control',
    'usability': 'Enhance usability for better user experience',
    'efficiency': 'Increase efficiency for better performance',
    'security': 'Enhance security features',
    'accuracy': 'Improve accuracy for better results',
    'stability': 'Enhance stability to prevent crashes',
    'flexibility': 'Increase flexibility for better adaptability',
    'visibility': 'Improve visibility for better readability',
    'comfort': 'Enhance comfort for better user experience',
    'maintenance': 'Reduce maintenance requirements',
    'installation': 'Simplify the installation process',
    'instructions': 'Provide clearer instructions',
    'documentation': 'Improve documentation for better understanding',
    'integration': 'Enhance integration with other systems',
    'functionality': 'Expand functionality for more use cases',
    'control': 'Improve control options for better management',
    'speed': 'Increase speed for faster results',
    'range': 'Extend the range for better coverage',
    'noise': 'Reduce noise levels',
    'temperature': 'Control temperature more effectively',
    'energy': 'Increase energy efficiency',
    'interface': 'Improve the interface for better user interaction',
    'response': 'Enhance response time',
    'capacity': 'Increase capacity for more usage',
    'brightness': 'Adjust brightness for better visibility',
    'contrast': 'Improve contrast for better display quality',
    'resolution': 'Increase resolution for clearer images',
    'sensitivity': 'Improve sensitivity for better detection',
    'strength': 'Increase strength for better durability',
    'power': 'Enhance power management',
    'portability': 'Improve portability for easier transport',
    'flexibility': 'Increase flexibility for better usage',
    'broken': 'Fix any broken parts',
}
